baseURL: 'http://vinoo.in/'
languageCode: en-us
title: Vinoo
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: blog
      name: Blog
      url: /blog
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
    # - identifier: experience
    #   name: Experience
    #   url: /experience
    #   weight: 40
    - identifier: search
      name: Search
      url: /search
      weight: 50
    - identifier: tags
      name: Tags
      url: /tags
      weight: 60
    - identifier: notes
      name: Notes
      url:/notes
      weight: 70

params:
  # theme 
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # Date
  dateFormat: "Jan 2, 2006"

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: '$whoami'
    subtitle: Hi 👋 I'm Vinoo, a software developer and programmer.
    # imageUrl: ''
    imageWidth: 220
    imageHeight: 220
    buttons:
      - name: Projects
        url: "/projects/"
      - name: Blog
        url: "/blog/"

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    # - name: 'linkedin'
    #   url: 'https://www.linkedin.com/in/ivinoop'
    - name: 'github'
      url: 'https://github.com/ivinoop'
    # - name: 'twitter'
    #   url: 'https://twitter.com/ivinoop'

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ['title', 'permalink', 'summary', 'content']

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
