# name: Publish to GH Pages
# on:
#   push:
#     branches:
#       - main
#   pull_request:

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout source
#         uses: actions/checkout@v3
#         with:
#           submodules: true

#       - name: Checkout destination
#         uses: actions/checkout@v3
#         if: github.ref == 'refs/heads/main'
#         with:
#           ref: gh-pages
#           path: built-site

#       - name: Setup Hugo
#         run: |
#           curl -L -o /tmp/hugo.tar.gz 'https://github.com/gohugoio/hugo/releases/download/v0.110.0/hugo_extended_0.110.0_linux-amd64.tar.gz'
#           tar -C ${RUNNER_TEMP} -zxvf /tmp/hugo.tar.gz hugo
#       - name: Build
#         run: ${RUNNER_TEMP}/hugo

#       - name: Deploy
#         uses: actions/checkout@v3
#         with:
#           personal_token: ${{ secrets.GITHUB_TOKEN }}
#           external_repository: ivinoop/site
#           publish_dir: ./public
#         # if: github.ref == 'refs/heads/main'
#         # run: |
#         #   cp -R public/* ${GITHUB_WORKSPACE}/built-site/
#         #   cd ${GITHUB_WORKSPACE}/built-site
#         #   git add .
#         #   git config user.name 'ivinoop'
#         #   git config user.email 'ivinoop@gmail.com'
#         #   git commit -m 'Updated site'
#         #   git push

#################################################

name: Deploy Hugo to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    - name: Build Hugo Site
      run: hugo  # This generates the static site in the "public/" folder

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub's auto-generated token
        external_repository: ivinoop/site  # Your public repo name
        publish_dir: ./public  # The directory with the static files
